# Generated by Django 4.1 on 2022-10-07 07:08

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_alter_department_title_alter_userinfo_create_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
            ],
        ),
    ]
