# Generated by Django 4.1 on 2022-10-14 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='number',
            field=models.CharField(default=999, max_length=64, verbose_name='任务号'),
            preserve_default=False,
        ),
    ]
