# Generated by Django 4.1 on 2022-10-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_task_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
