# Generated by Django 4.1 on 2022-10-14 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_delete_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64, verbose_name='任务号')),
                ('title', models.CharField(max_length=64, verbose_name='标题')),
                ('level', models.SmallIntegerField(choices=[(1, '紧急'), (2, '重要'), (3, '次要')], default=1, verbose_name='级别')),
                ('detail', models.TextField(verbose_name='详细信息')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='负责人')),
            ],
        ),
    ]
