# Generated by Django 4.1 on 2022-11-16 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_userinfo_depart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.admin', verbose_name='负责人'),
        ),
    ]
