# Generated by Django 4.1 on 2022-11-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0012_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='img',
        ),
        migrations.RemoveField(
            model_name='file',
            name='username',
        ),
        migrations.AddField(
            model_name='file',
            name='detail',
            field=models.CharField(default='qqq', max_length=64, verbose_name='文件描述'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.CharField(default='www', max_length=64, verbose_name='文件路径'),
            preserve_default=False,
        ),
    ]
