# Generated by Django 4.1 on 2022-11-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0014_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='username',
            new_name='administrator',
        ),
    ]
