# Generated by Django 4.1 on 2022-11-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0015_rename_username_image_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_path',
            field=models.FileField(max_length=64, upload_to='img/', verbose_name='图片路径'),
        ),
    ]
