# Generated by Django 4.1 on 2022-11-19 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0016_alter_image_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='administrator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', unique=True, verbose_name='管理员'),
        ),
    ]
