# Generated by Django 4.1 on 2022-11-19 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0018_alter_image_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='administrator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.admin', verbose_name='管理员'),
        ),
    ]
